.github/workflows/Main.yml
.github/workflows/build-msvc-workflow.yml
.github/workflows/build-workflow.yml
.github/workflows/cppcheck.yml
.github/workflows/deploy-workflow.yml
.github/workflows/release-workflow.yml
.github/workflows/test-msvc-workflow.yml
.github/workflows/test-workflow.yml

This pull request adds a GitHub Actions workflow to test the codebase on multiple platforms, ensuring compatibility and stability across different environments. The platforms included in this CI pipeline are:
- **amd64 (x86_64)**: Standard architecture for most development environments.
- **arm64**: Commonly used in mobile devices, IoT, and some servers.
- **msvc**: Microsoft's Visual C++ environment for Windows applications.
Key features of this workflow:
- Runs automated tests on the mentioned platforms using matrix strategy in GitHub Actions.
- Ensures that the code compiles and runs correctly on each platform.
- Validates cross-platform functionality and catches platform-specific issues early.
Please review the workflow and provide feedback.

CI: Add GitHub Actions to test on multiple platforms (amd64, arm64, msvc)

---

document/sphinx-cn/tutorials/quick_start/build_from_source_windows.md
src/examples/plugins/iceoryx_plugin/install/linux/bin/start_examples_plugins_iceoryx_plugin_ros2_chn_pub.sh
src/examples/plugins/iceoryx_plugin/install/linux/bin/start_examples_plugins_iceoryx_plugin_ros2_chn_sub.sh

- fix iceoryx plugin ros2 example srcipts
- fix doc

fix iceoryx plugin example

---

url_cn.bashrc

Enhance dependency management by aligning jsoncpp and asio download links with AimRT repositories.

build: update download URLs for dependencies

---

document/sphinx-cn/release_notes/v0_9_0.md
document/sphinx-cn/tutorials/examples/examples_py.md
src/examples/cpp/pb_chn/module/benchmark_subscriber_module/benchmark_subscriber_module.cc
src/examples/py/helloworld/README.md
src/examples/py/parameter/README.md
src/examples/py/pb_chn/README.md
src/examples/py/pb_chn_bench/README.md
src/examples/py/pb_chn_bench/benchmark_publisher_app.py
src/examples/py/pb_chn_bench/benchmark_publisher_module.py
src/examples/py/pb_chn_bench/benchmark_subscriber_app.py
src/examples/py/pb_chn_bench/benchmark_subscriber_module.py
src/examples/py/pb_chn_bench/build_py_pb_chn.sh
src/examples/py/pb_chn_bench/cfg/benchmark_publisher_cfg.yaml
src/examples/py/pb_chn_bench/cfg/benchmark_subscriber_cfg.yaml
src/examples/py/pb_chn_bench/start_benchmark_publisher.sh
src/examples/py/pb_chn_bench/start_benchmark_subscriber.sh
src/examples/py/pb_rpc/README.md
src/protocols/example/benchmark.proto

Introduce new benchmark publisher and subscriber modules, enabling performance testing with custom configuration. Includes necessary YAML configuration files and scripts for simulation of message publishing and receiving.

feat: add aimrt_py benchmark publisher and subscriber applications

---

src/examples/py/pb_chn_bench/README.md
src/examples/py/pb_chn_bench/benchmark_publisher_module.py
src/examples/py/pb_chn_bench/benchmark_subscriber_module.py
src/examples/py/pb_rpc_bench/benchmark_rpc_client_module.py
src/protocols/example/benchmark.proto

Streamline benchmarking process by eliminating shutdown peer signal handling, simplifying the code and improving clarity.
Maintain logical consistency with the benchmark program's C++ version.

refactor: remove shutdown peer logic from publisher and subscriber

---

document/sphinx-cn/tutorials/interface_py/channel.md
document/sphinx-cn/tutorials/interface_py/rpc.md
src/examples/py/pb_rpc/examples_py_pb_rpc_client_app.py
src/examples/py/pb_rpc/examples_py_pb_rpc_server_app.py
src/runtime/python_runtime/export_rpc.h

* Add documentation for aimrt_py rpc context
* Modify aimrt_py rpc example to show context usage
* Export context GetType return value enum type into python

docs: add aimrt_py rpc context

---

src/tools/package_aimrt_py/pyproject.toml

Change the email address of Zhang Yi to reflect current contact information.

chore: update author email for Zhang Yi

---

src/runtime/core/logger/console_logger_backend.cc
src/runtime/core/logger/logger_manager.cc
src/runtime/core/logger/logger_proxy.h
src/runtime/core/logger/rotate_file_logger_backend.cc
src/runtime/core/logger/rotate_file_logger_backend.h

update logger module
- update code comments
- update some check

fix: update logger

---

document/sphinx-cn/release_notes/v0_9_0.md
document/sphinx-cn/tutorials/plugins/grpc_plugin.md
src/examples/plugins/grpc_plugin/README.md
src/examples/plugins/grpc_plugin/install/linux/bin/cfg/examples_plugins_grpc_plugin_ros2_rpc_client_cfg.yaml
src/examples/plugins/grpc_plugin/install/linux/bin/cfg/examples_plugins_grpc_plugin_ros2_rpc_server_cfg.yaml
src/examples/plugins/grpc_plugin/install/linux/bin/start_examples_plugins_grpc_plugin_ros2_rpc_client.sh
src/examples/plugins/grpc_plugin/install/linux/bin/start_examples_plugins_grpc_plugin_ros2_rpc_server.sh
src/plugins/grpc_plugin/client/options.h
src/plugins/grpc_plugin/grpc_rpc_backend.cc
src/plugins/grpc_plugin/grpc_rpc_backend.h
src/plugins/grpc_plugin/server/options.h

* Provides ROS2 and JSON serialization format support for the gRPC plugin
* Adds ROS2 example configuration and launch scripts for the gRPC plugin
* Adds corresponding documentation.

feat: add json and ros2 serialization support for grpc plugin

---

src/common/util/log_util.h

fix:  repair kLvlNameArray oversize

---

src/interface/aimrt_module_cpp_interface/module_base.h

feat: improve modulebase

---

CMakeLists.txt
build.bat
build.sh
src/runtime/core/util/dynamic_lib.h
src/runtime/core/util/rpc_client_tool_test.cc
src/runtime/core/util/thread_tools_test.cc
src/runtime/core/util/type_support_pkg_loader.cc
src/runtime/core/util/type_support_pkg_loader.h
src/runtime/core/util/yaml_tools.cc

- fix some minor bug
- optimize code comments

fix: runtime/core/util

---

document/sphinx-cn/release_notes/v0_9_0.md
document/sphinx-cn/tutorials/cfg/executor.md
src/examples/cpp/pb_chn/module/benchmark_publisher_module/benchmark_publisher_module.cc
src/runtime/core/executor/asio_strand_executor.cc
src/runtime/core/executor/asio_strand_executor.h
src/runtime/core/executor/asio_thread_executor.cc
src/runtime/core/executor/asio_thread_executor.h
src/runtime/core/executor/asio_thread_executor_test.cc
src/runtime/core/executor/simple_thread_executor.cc
src/runtime/core/executor/simple_thread_executor.h
src/runtime/core/executor/simple_thread_executor_test.cc
src/runtime/core/executor/tbb_thread_executor.cc
src/runtime/core/executor/tbb_thread_executor.h

- executor can use system clock or steady clock

feat: executor sys clock

---

src/plugins/grpc_plugin/grpc_rpc_backend.cc
src/plugins/net_plugin/http/http_rpc_backend.cc

Improve error handling for async wait operations in both RPC backends by catching system errors, ensuring robustness against cancellations. This change addresses potential crashes and enhances stability during RPC service handling.

fix: handle timer exceptions in grpc and http rpc backends

---

document/sphinx-cn/conf.py
src/plugins/echo_plugin/echo_plugin.cc
src/runtime/core/channel/channel_manager.cc
src/runtime/core/executor/executor_manager.cc
src/runtime/core/logger/logger_manager.cc
src/runtime/core/plugin/plugin_manager.cc
src/runtime/core/rpc/rpc_manager.cc

fix: yaml misc

---

src/examples/py/pb_rpc_bench/benchmark_rpc_client_module.py
src/runtime/python_runtime/export_pb_type_support.h
src/runtime/python_runtime/export_ros2_type_support.h
src/runtime/python_runtime/ros2_type_support_utils.cc
src/runtime/python_runtime/ros2_type_support_utils.h

By the way remove some unused include for aimrt_py.

fix: enhance error handling in RPC benchmark client for aimrt_py

---

src/tools/protoc_plugin_py_gen_aimrt_py_rpc/protoc_plugin_py_gen_aimrt_py_rpc.py

Improve the import structure by replacing a relative import with an absolute import format. This enhances readability and maintains consistency in the codebase.

refactor: update import statement for better clarity

---

src/examples/py/pb_rpc_bench/benchmark_rpc_client_module.py

- Introduced a new method `WaitForServiceServer` to ensure the service server is available before starting benchmarks.
- Added a timeout mechanism for RPC calls to improve robustness.
- Enhanced logging to provide feedback on server availability during the benchmark process.

feat: add service server wait functionality in BenchmarkRpcClientModule

---

src/examples/plugins/record_playback_plugin/install/linux/bin/cfg/examples_plugins_record_playback_plugin_record_ros2_imd_cfg.yaml
src/examples/plugins/record_playback_plugin/install/linux/bin/start_examples_plugins_record_playback_plugin_record_ros2_imd.sh
src/plugins/proxy_plugin/proxy_plugin.cc

1. add proxy cache to avoid the deserialize step
2. update launch scripts to load ROS2 environment

perf: add proxy cache to avoid the deserialize step

---

src/plugins/grpc_plugin/server/connection.h

- Improved the handling of incoming requests by checking the size of the request list and sending appropriate responses when no requests are present.
- Introduced a new `SubmitAndSend` method to streamline the submission of responses to the nghttp2 session, enhancing code clarity and maintainability.
- Updated error handling to log warnings for unregistered URLs and ensure proper response generation for bad requests.
- Refactored the request processing loop to utilize `asio::co_spawn` for concurrent handling of requests, improving performance and responsiveness.
Fixes #174

refactor: enhance request handling and response submission in gRPC connection  

---

document/sphinx-cn/tutorials/quick_start/installation_py.md

- Clarify plugin and message type support for AimRT-Python
- Highlight configuration file compatibility with AimRT-Cpp
- Note limitations of RPC interfaces in Python implementation

docs: update AimRT-Python installation documentation

---

document/sphinx-cn/build.sh
document/sphinx-cn/conf.py

- Add v0.10.0-rc1 to documentation versions
- Update Sphinx multiversion tag whitelist
- Modify build script to copy only index.html

docs: update documentation version configuration

---

document/sphinx-cn/release_notes/v0_10_0.md
src/plugins/grpc_plugin/server/connection.h

fix(grpc_plugin): set tick_has_data_ to true when received request

---

document/sphinx-cn/release_notes/v0_10_0.md
src/plugins/grpc_plugin/client/connection.h

Ref: https://github.com/nghttp2/nghttp2/issues/1046#issuecomment-341863998
Close #223 .

fix(grpc_plugin): send big data chunks until ending in the client side

---

document/sphinx-cn/release_notes/v0_10_0.md
src/common/util/sys_tools.h
src/runtime/core/aimrt_core.cc
src/runtime/core/configurator/configurator_manager.cc

print executable pid and path in Initialization report

---

document/sphinx-cn/release_notes/v1_0_0.md
document/sphinx-cn/tutorials/interface_cpp/executor.md
src/examples/cpp/executor/module/timer_module/timer_module.cc
src/interface/aimrt_module_cpp_interface/executor/timer.h
src/plugins/record_playback_plugin/record_action.cc
src/plugins/topic_logger_plugin/topic_logger_backend.h
src/runtime/core/logger/rotate_file_logger_backend.h

- Removed unnecessary SyncWait calls in TimerModule and Timer class.
- Streamlined the Shutdown method in TimerModule for better readability.
- Updated Timer constructor to always cancel the timer, removing the auto_start parameter.
- Enhanced ExecuteLoop method to use shared pointers for better memory management.

refactor: simplify TimerModule and Timer class shutdown logic
