AimRT/AimRT

.github/workflows/Main.yml
This update improves our CI/CD process with two key changes:
1. Automated wheel package upload for releases:
- Implement automatic uploading of .whl packages when a new release is created.
- This streamlines our release process and ensures consistent package distribution.
2. Rename PR label from "reviewed" to "ci ready":
- Change the label that triggers CI checks from "reviewed" to "ci ready".
- This new label name more clearly communicates its purpose in the CI workflow.
- Update all related documentation and workflow files to reflect this change.
=>  CI : Add auto-upload for releases and refine PR labeling

.github/workflows/release-workflow.yml
This update improves our CI/CD process with two key changes:
Automated wheel package upload for releases:
Implement automatic uploading of .whl packages when a new release is created.
This streamlines our release process and ensures consistent package distribution.
Rename PR label from "reviewed" to "ci ready":
Change the label that triggers CI checks from "reviewed" to "ci ready".
This new label name more clearly communicates its purpose in the CI workflow.
Update all related documentation and workflow files to reflect this change.
=> CI : Add auto-upload for releases 

src/plugins/grpc_plugin/CMakeLists.txt, src/plugins/grpc_plugin/grpc/message.h
Ensure compatibility on Windows by defining ssize_t as int for the gRPC plugin. This adjustment prevents potential type-related issues during compilation.
Fix https://github.com/AimRT/AimRT/issues/17 problem 2.
=> build: add Windows specific compile option for ssize_t

CMakeLists.txt
Streamline CMake configuration by consolidating compiler options and ensuring consistent export of compile commands, enhancing the build process especially for MSVC and Windows environments.
Fix https://github.com/AimRT/AimRT/issues/17 problem 1
=> build: reorganize CMake configuration to fix windows build by fetchcontent

cmake/GetBoost.cmake
Streamline the process of finding and downloading Boost by removing unnecessary checks and consolidating the logic, making it easier to manage and maintain dependencies.
=> build: simplify Boost fetching logic

document/sphinx-cn/release_notes/v0_9_0.md, src/runtime/python_runtime/export_channel.h, src/runtime/python_runtime/export_rpc.h
Protect the access to the pybind11::bytes object with a GIL lock to avoid potential memory errors, and unify the handling of empty and non-empty strings. 
Eliminate unused functions for empty byte objects in the export channel and export RPC modules to enhance code clarity.
=> fix: add GIL for pybind11::bytes object accessing

document/sphinx-cn/tutorials/interface_py/rpc.md
Clarify the requirement for specifying a package name in proto files to ensure successful RPC code generation in Python.
=> docs: add package specification and generation note for proto files

CMakeLists.txt
Set CMAKE_POSITION_INDEPENDENT_CODE to ON to ensure compatibility with shared libraries and enhance portability across different architectures. Removed explicit compiler flags for PIC that were previously set.
Fix https://github.com/AimRT/AimRT/issues/41 .
=> build: enable position-independent code

src/examples/py/pb_chn_bench/benchmark_publisher_module.py, src/examples/py/pb_chn_bench/benchmark_subscriber_module.py, src/examples/py/pb_rpc_bench/benchmark_rpc_client_module.py
- ensure subscriber receives all messages before ending
- optimize timestamp retrieval for benchmarking
=> fix: aimrt_py channel benchmark for large data packets

src/examples/py/pb_chn_bench/benchmark_publisher_module.py, src/examples/py/pb_chn_bench/benchmark_subscriber_module.py, src/examples/py/pb_rpc_bench/benchmark_rpc_client_module.py
Update timestamp handling in both publishing and subscribing modules to use time.time_ns() instead of time.perf_counter_ns(). This change improves consistency in timestamp precision and ensures uniformity across the system's message timing functionalities.
=> fix: standardize timestamp handling with time.time_ns()

document/sphinx-cn/tutorials/interface_py/channel.md, src/examples/py/pb_chn/examples_py_pb_chn_publisher_app.py, src/examples/py/pb_chn/examples_py_pb_chn_subscriber_app.py, src/runtime/python_runtime/aimrt_py_pb_chn.py, src/runtime/python_runtime/export_channel.h
* Add documentation related to the aimrt_py channel context.
* Add aimrt_py channel context usage examples.
* Fix issue where the return value of the GetType method was not exported.
* Fixed an error when context serialization type was not set.
=> docs: add aimrt_py channel context 

src/examples/py/pb_rpc_bench/benchmark_rpc_client_module.py
Include frequency details in the benchmark report when using fixed frequency mode to enhance clarity and analysis of performance metrics.
=> feat: add frequency information to benchmark report

src/common/net/asio_http_cli.h
- Updated coroutines to capture request objects by value instead of by reference to prevent potential dangling references.
- Modified client_key generation by adding a ':' separator between host and service to ensure each key is unique.
=> Refactor coroutine request handling and ensure unique client keys

src/tools/protoc_plugin_py_gen_aimrt_py_rpc/protoc_plugin_py_gen_aimrt_py_rpc.py
Enhance the generation of message type names by ensuring proper handling of package and message components, eliminating excess separators for cleaner output.
=> fix: code gen error for proto files without package declaration

document/sphinx-cn/tutorials/interface_py/rpc.md
Remove outdated note about file generation failure due to missing package name in proto files to enhance clarity and usability for developers.
Already fixed by https://github.com/AimRT/AimRT/pull/62 .
=> docs: update rpc documentation to clarify package name requirement

CMakeLists.txt, cmake/GetAsio.cmake, cmake/GetBoost.cmake, cmake/GetCppToml.cmake, cmake/GetFmt.cmake, cmake/GetGFlags.cmake, cmake/GetGTest.cmake, cmake/GetIceoryx.cmake, cmake/GetJsonCpp.cmake, cmake/GetLibUnifex.cmake, cmake/GetNghttp2.cmake, cmake/GetNlohmannJson.cmake, cmake/GetOpenTelemetryCpp.cmake, cmake/GetOpenTelemetryProto.cmake, cmake/GetProtobuf.cmake, cmake/GetPybind11.cmake, cmake/GetSqlite.cmake, cmake/GetStdexec.cmake, cmake/GetTBB.cmake, cmake/GetYamlCpp.cmake, cmake/GetZenoh.cmake
Wrap multiple CMake scripts in functions to restrict variable scope and prevent unintended resets. This ensures better modularity and maintainability in the build process while adhering to modern CMake best practices.
=> build: refactor CMake scripts to use functions for variable scope

CMakeLists.txt
Ensure that the local `protoc` compiler is found when `AIMRT_USE_LOCAL_PROTOC_COMPILER` is enabled. This improves setup reliability by providing clear feedback if `protoc` is missing, helping users avoid runtime issues.
Fix missing YamlCpp dependency when building with ROS2.
Closes #88 .
=> fix: add error handling for local protoc compiler detection

CMakeLists.txt, src/examples/plugins/ros2_plugin/CMakeLists.txt, src/plugins/CMakeLists.txt
Add dependent options for building various plugins and components, allowing finer control over runtime and external library usage. This change improves flexibility and ensures that components are only built when their dependencies are active, optimizing the build process.
=> build: enhance build options for modular components

src/runtime/core/aimrt_core.cc, src/runtime/core/aimrt_core.h, src/runtime/core/util/version.h
Include a method to print detailed startup information about the framework, enhancing user awareness of the version and providing relevant links for support.
Close #106 .
=> feat: add startup info printing during initialization

src/examples/plugins/grpc_plugin/install/linux/bin/start_examples_plugins_grpc_plugin_pb_rpc_client.sh, src/examples/plugins/grpc_plugin/install/linux/bin/start_examples_plugins_grpc_plugin_pb_rpc_server.sh, src/plugins/grpc_plugin/server/server.h
- Added a new method `CheckListenAddr` to validate the listening address for the server.
- Integrated error checking in the server initialization to throw an exception if the address is already in use, improving robustness and error handling.
- Eliminated the lines that forcefully kill processes listening on ports 50050 and 50051 in the gRPC plugin start scripts. This change simplifies the startup process and avoids potential issues with abrupt terminations.
=> fix: enhance error checking for server listen address in gRPC plugin

src/runtime/core/channel/local_channel_backend.h
Updated the SubscribeIndexMap in LocalChannelBackend to use std::string instead of std::string_view for msg_type, topic, lib_path, and module_name. This change enhances memory management and ensures proper ownership semantics for string data within the subscription index map.
=> fix: change string_view to string in LocalChannelBackend subscription index map

document/sphinx-cn/tutorials/quick_start/build_from_source_windows.md, document/sphinx-cn/tutorials/quick_start/installation_py.md
- Added a note regarding the MSVC toolset version 19.40 for Visual Studio 2022 to address potential compilation issues.
- Updated the installation methods for the `aimrt_py` package, clarifying that PyPI installation is not currently supported and emphasizing source compilation as the recommended method.
=> docs: update Windows build instructions and clarify installation methods

document/sphinx-cn/tutorials/cfg/rpc.md
- Fixed typos in the RPC documentation, specifically changing "正真的" to "真正的" and "Contxet" to "Context".
- Enhanced the clarity of the text to ensure better understanding of the RPC method handling process in AimRT.
=> docs: correct typos and improve clarity in RPC documentation

src/plugins/ros2_plugin/ros2_adapter_rpc_client.cc, src/plugins/ros2_plugin/ros2_adapter_rpc_server.cc
- Updated the context reservation in `ros2_adapter_rpc_client.cc` to accommodate an additional timeout value.
- Modified the context parsing in `ros2_adapter_rpc_server.cc` to correctly handle the new timeout value and adjust the indexing for key-value pairs accordingly.
=> fix: adjust context handling in ROS2 adapter RPC client and server

document/sphinx-cn/tutorials/interface_cpp/rpc.md, document/sphinx-cn/tutorials/misc/questions.md
- Update the table description for rpc status codes
- Update special notes on rpc status when using ros2 rpc backend and ros2 srv together
=> docs: update RPC status-related documentation

src/examples/utils/run_all_example.py
- Updated the ExampleRunner class in run_all_example.py to read the package version from the VERSION file instead of hardcoding it. This change enhances flexibility and ensures that the correct version is installed during the example execution.
=> feat: dynamically read package version from VERSION file in example runner

src/plugins/mqtt_plugin/mqtt_plugin.cc
- Enhanced the error logging in the MQTT plugin to provide clearer messages when connection attempts fail.
- Updated the failure callback to handle cases where the response message may be null, ensuring that a more informative message is logged.
=> fix: improve MQTT connection failure logging

src/interface/aimrt_module_cpp_interface/rpc/rpc_context.h
- Added std::pmr::monotonic_buffer_resource for efficient memory allocation in RPC context
- Introduced a small static buffer to reduce dynamic memory allocations
- Updated meta_data_map_ and meta_keys_vec_ to use polymorphic memory resources
- Added a copy constructor and move constructor to support PMR-based memory management
=> refactor: optimize RPC context memory management with PMR

document/sphinx-cn/release_notes/v0_10_0.md, src/interface/aimrt_module_cpp_interface/channel/channel_context.h, src/interface/aimrt_module_cpp_interface/rpc/rpc_context.h
- Implement memory optimization for channel context using std::pmr::monotonic_buffer_resource
- Add a static buffer to reduce dynamic memory allocations
- Update meta_data_map_ and meta_keys_vec_ to use polymorphic memory resources
- Enhance copy and move constructors to support PMR-based memory management
- Delete copy and move assignment operators to prevent unintended object copying
=> refactor: optimize channel context memory management with PMR

document/sphinx-cn/tutorials/quick_start/helloworld_cpp.md
Add `CMAKE_POLICY_DEFAULT_CMP0077` to ensure consistent CMake configuration behavior across different environments
=> fix: add CMake policy for consistent configuration

src/examples/cpp/pb_chn/module/normal_publisher_module/normal_publisher_module.cc, src/examples/cpp/pb_chn/module/normal_publisher_module/normal_publisher_module.h
- Initialize `run_flag_` to false by default
- Set `run_flag_` to true when starting the module
- Add a check in Shutdown to prevent unnecessary future waiting
=> fix: improve NormalPublisherModule start and shutdown logic

src/examples/py/pb_chn/build_examples_py_pb_chn.sh, src/examples/py/pb_chn_bench/README.md, src/examples/py/pb_chn_bench/benchmark_subscriber_module.py, src/examples/py/pb_chn_bench/build_py_pb_chn.sh, src/examples/py/pb_rpc/build_examples_py_pb_rpc.sh, src/examples/py/pb_rpc_bench/build_examples_py_pb_rpc_bench.sh, src/examples/py/ros2_rpc/README.md, src/examples/py/ros2_rpc/build_examples_py_ros2_rpc.sh
- Adapt examples protocols to new path introduced by #248 .
- Fix broken benchmark introduced by #246 .
=> fix: make python examples and benchmark work as before

cmake/GetAsio.cmake, cmake/GetFmt.cmake, cmake/GetTBB.cmake, cmake/GetYamlCpp.cmake
Only Asio, fmt, Tbb, and YamlCpp supports it.
Paho-mqtt-c, Libunifex, and Json-cpp sucks.
=> refactor: conditionally enable installation for some dependencies

CMakeLists.txt, document/sphinx-cn/build.sh
Added support for the --single-version argument in the build script. The script now checks if it's running in a Git repository and builds documentation accordingly, using sphinx-multiversion for multi-version or sphinx-build for single version or non-Git repositories.
=> feat: enhance build script to support single version documentation

cmake/GetMcap.cmake
=> fix: correct variable name for zstd source directory in CMake configuration
